services:

  # If you change this then update the service name for the main container in .devcontainer/devcontainer.json.
  app:

    # Build it from this directory.
    build: .

    # Repo name
    container_name: lstm_mionet_container

    # Stop the container from exiting right after start.
    tty: true
    stdin_open: true

    # Link the files here to the code directory in the container.
    volumes:
      - .:/LSTM-MIONet:cached
    
    # Uncomment this to enable GPU support if you have a GPU machine.
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 2
    #           capabilities: [gpu]